config/routes.rb
Rails.application.routes.draw do


  devise_for :admins
  devise_for :users
  
  root 'products#index'
  
  resource :basket, only: %i(show)
  resource :charge, only: %i(create)
  resource :sales_record, only: %i(show)
  
  
  
  resources :products, only: %i(show) do
    scope module: :products do
      resources :add_to_baskets, only: %i(create)
      resources :delete_in_baskets, only: %i(create)
    end
  end
  
  namespace :admins do
    root to: "dashboards#index"
    resources :products, only: %i(new create edit update destroy)
    resource :sales_record, only: %(show)
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/basket.rb
# == Schema Information
#
# Table name: baskets
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Basket < ApplicationRecord
  # basketは複数のbasket_products（中間レコード）を持っている。:destroy basket_productsが0になると、basketも自動的に削除される
  has_many :basket_products, dependent: :destroy
  # basketは複数のproductsを持っている。through:basketから直接productsを呼べる
  has_many :products, through: :basket_products
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!

  def show
    basket = current_user.basket || current_user.create_basket
    @products = basket.products
    @total_price = @products.sum(:price)
  end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/views/baskets/show.html.haml
.container.text-center
  %h3.mb-30
    買い物かごの中身
  %table
    %thead
      %tr
        %th 商品名
        %th 価格
        %th 削除
    %tbody
      - @products.each do |product|
        %tr
          %td
            = product.name
          %td.text-right
            = product.price
            円
          %td.text-center
            = link_to product_delete_in_baskets_path(product), method: :post, data: {confirm: '削除してもいいですか？'} do
              %span.basket__delete
                ✕
  .basket__total-amount.right
    合計金額 #{@total_price} 円
    
  = form_tag charge_path do
    - @products.each do |p|
      = hidden_field_tag 'product_ids[]', p.id
    = submit_tag "決済"