config/routes.rb
Rails.application.routes.draw do


  devise_for :admins
  devise_for :users
  
  root 'products#index'
  
  resource :basket, only: %i(show)
  resource :charge, only: %i(create)
  resource :sales_record, only: %i(show)
  
  
  
  resources :products, only: %i(show) do
    scope module: :products do
      resources :add_to_baskets, only: %i(create)
      resources :delete_in_baskets, only: %i(create)
    end
  end
  
  namespace :admins do
    root to: "dashboards#index"
    resources :products, only: %i(new create edit update destroy)
    resource :sales_record, only: %(show)
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  admin_id    :integer          not null
#  name        :string           not null
#  description :text             not null
#  price       :integer          not null
#  image       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :basket_products, dependent: :destroy
  has_many :purchase_record_products, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true

  include Hashid::Rails

  belongs_to :admin
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < Admins::ApplicationController
  # 他テーブルと関連付けがあるものは慣例的にbuild。build=new
  def new
    @product = current_admin.products.build
  end

  def create
    @product = current_admin.products.build(product_params)
    if @product.save
      redirect_to root_path, notice: '商品を登録しました'
    else
      flash[:error] = '商品の登録に失敗しました'
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(
      name: product_params[:name],
      description: product_params[:description],
      price: product_params[:price],
      image: product_params[:image]
    )
      flash[:notice] = '保存に成功'
      redirect_to root_path
    else
      flash[:notice] = '保存に失敗'
      redirect_to edit_admins_product_path
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = '商品を削除しました'
    redirect_to root_path
  end

  # 不正な値を受け取らないよう、permitに許可する値を記載
  # private=class外では呼び出せない
  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/controllers/products/add_to_baskets_controller.rb
class Products::AddToBasketsController < Products::ApplicationController
  def create
    basket = current_user.basket || current_user.create_basket
    product = Product.find(params[:product_id])
    basket.basket_products.create!(product_id: product.id)

    redirect_to basket_path
  end
end

app/controllers/products/application_controller.rb
class Products::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/products/delete_in_baskets_controller.rb
class Products::DeleteInBasketsController < Products::ApplicationController
  def create
    basket = current_user.basket || current_user.create_basket
    product = Product.find(params[:product_id])
    # 中間レコード(basketの中身)削除
    basket_product = basket.basket_products.find_by(product_id: product.id)
    basket_product.destroy!

    redirect_to basket_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(20)
    if @q = Product.ransack(params[:q])
      @products = @q.result.page(params[:page]).per(20)
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.haml
#container
  %h4#title 
    取り扱いワイン一覧(
    = page_entries_info @products
    )
  #sidebar.text-center
    = search_form_for @q, url: root_path do |f|
      = f.search_field :name_cont, class:'searchform', :placeholder => "名前を入れて検索"
      = f.submit class:'submitbutton'
  #main
    - @products.each do |product|
      #item.border-bottom
        %p#productimg
          - if product.image.present?
            = image_tag product.image_url
          - else
            = link_to(image_tag("/no-image-min.jpg"),product)
        %p.w-auto
          = link_to product.name, product_path(product.id)
        %span.text-danger #{product.price} 円
        %br
        %span.w-auto.overflow-hidden
          = product.description
#paginate
  = paginate @products

app/views/products/new.html.haml
%h2.center
  新規商品の追加
.container
  = simple_form_for @product do |f|
    = f.input :name
    = f.input :description
    = f.input :price
    = f.input :image, as: :file, input_html: {accept: ("image/jpg,image/jpeg,image/gif,image/png")}
    .mt-20
      = f.button :submit

app/views/products/show.html.haml
%h2.text-center  商品詳細
.text-center
  #show.d-inline-block.border
    .d-inline-block.w-100.h-auto
      - if @product.image.url.present?
        = image_tag @product.image.url
      - else
        = image_tag "bottle3.jpg"
    .d-inline-block
      %span 商品名：
      %span= @product.name
      %br
      %span 商品説明：
      %span= @product.description
      %br
      %span 価格：
      %span= @product.price
      %br
    = link_to product_add_to_baskets_path(@product), method: :post do
      .pt-1.pb-2.border-0.btn.btn-warning 買い物かごに入れる
    .product
      - if current_admin.present?
        = link_to  edit_admins_product_path(@product), method: :get do
          .btn.btn-danger.mt-1 編集
        = link_to admins_product_path(@product), method: :delete do
          .btn.btn-danger.mt-1 消去