config/routes.rb
Rails.application.routes.draw do


  devise_for :admins
  devise_for :users
  
  root 'products#index'
  
  resource :basket, only: %i(show)
  resource :charge, only: %i(create)
  resource :sales_record, only: %i(show)
  
  
  
  resources :products, only: %i(show) do
    scope module: :products do
      resources :add_to_baskets, only: %i(create)
      resources :delete_in_baskets, only: %i(create)
    end
  end
  
  namespace :admins do
    root to: "dashboards#index"
    resources :products, only: %i(new create edit update destroy)
    resource :sales_record, only: %(show)
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wineport
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -if flash[:notice]
      %p.notice= notice
    -if flash[:alert]
      %p.alert= alert
    %nav
      .nav-wrapper.pt-3.pb-1.align-middle.pr-2.d-flex.justify-content-between
        = link_to image_tag("/wineport.jpg"), root_path, class: "pl-3"
        %ul#nav-mobile.right.hide-on-med-and-down.text-right.list-unstyled.list-inline
          - if current_user.present?
            %li.list-inline-item
              = link_to '買い物かご', basket_path
            %li.list-inline-item
              = link_to '購入履歴', sales_record_path
            %li.list-inline-item
              = link_to 'ログアウト', destroy_user_session_path, method: :delete
          - else 
            %li.list-inline-item
              = link_to 'ログイン', new_user_session_path
          - if current_admin.present?
            %li.list-inline-item
              = link_to '出品管理(アドミン)', new_admins_product_path, method: :get
            %li.list-inline-item
              = link_to '購入履歴(アドミン)', admins_sales_record_path, method: :get
            %li.list-inline-item
              = link_to 'ログアウト(アドミン)', destroy_admin_session_path, method: :delete
          - else
            %li.list-inline-item
              = link_to '出品者ログイン（アドミン）', new_admin_session_path
    = yield